### ISSUE TITLE
List any issues closed does not work

### ISSUE THREAD

**Issue by moltar** [KnisterPeter/vscode-commitizen#639] opened 2021-11-04 11:51 UTC
Adding any value into the "list any issues closed" input does not save those value.

Commit message only contains the short message.

**Comment by KnisterPeter** [comment] 2021-11-17 07:25
@moltar This is a duplicate of https://github.com/KnisterPeter/vscode-commitizen/issues/595
Please provide a PR

**Closed by KnisterPeter** 2021-11-17 07:25 UTC
